### ISSUE TITLE
findIndex Method Problem

### ISSUE THREAD

**Issue by kurtiyil** [jazz-community/rtc-workitem-bulk-mover-ui#11]
Hi,
We test the plugin with IE 11 and getting error about findIndex method in bulk-mover.js. I think IE 11 doesn't support the method.
Thank you.

**Comment by innerjoin** [comment]
@kurtiyil Thank you for your bug report. You are right, according to MDN, Internet Explorer doesn't support the `findIndex`. 
Backports to ES5 compatible browsers are made with babel, but it seems that we only backport ES2015 features, instead of all of them (ES2015, ES2016, ES2017). 

**Solution**
Replace npm package `babel-preset-es2015` with `babel-preset-env` and update its usage in `webpack.config.js`

**Comment by innerjoin** [comment]
Sorry for the late reply, I struggled with the migration to `babel-preset-env`. I will try this as soon as possible again, hopefully it works.
