### ISSUE TITLE
Moved work items do not appear in queries and have an incorrect type

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-workitem-bulk-mover-ui#4]
**Original Issue Description**
A few users have reported that in some cases work items were not caught by queries after moving them to a SAFe based project area. To resolve this inconsistency, one has to open the work item, change the type to the wanted type and save it again. 

**Reason**
The move implementation of IBM cannot handle different process descriptions (e.g. from SCRUM to SAFe), where the type cateogry is the same (e.g. task or defect), but the identification is not.

**Consequences**
The work item is identified as a defect from the source project area but it looks like the intended work item type of the target project area (e.g. task). This is also the reason why work items cannot be found by queries

**Comment by innerjoin** [comment]
Investigation has shown that this issue is related to the internal move implementation, as also used by the single move functionality within the work item editor. We currently have a PMR open with IBM to resolve this issue.

refer to the updated issue description to learn about the consequences

**Comment by schneigu** [comment]
There are to issues here
a ) the bulk mover is not recognizing there is no workitem with the ID "task" in the target process.
b) the builtin move workitem function is mapping the workitem to the default workitem type "defect", because of the missing "task", but is doing thus only half way. This cause the workitem in a completely wrong state.

What can we do:
a) We must better detect, if there is a workitem type availalable in target. We must check for exact id.
b) I have a PMR open and I'm in discussion with IBM. First reaction was "works as designed".

**Comment by innerjoin** [comment]
In terms of **a)**, I was already working on a detection mechanism to prevent the misbehavior if the IBM implementation. It is now ready to use and provided with the latest [1.1.2 Release](https://github.com/jazz-community/rtc-workitem-bulk-mover-service/releases/tag/v1.1.2) of the Bulk Mover Service.

regarding **b)**, to track our open IBM PMR, I'll keep this issue open as long as we know IBMs final decision on whether they fix or leave it.

**Comment by innerjoin** [comment]
You can follow the resolution of the root issue on Jazz.net: https://jazz.net/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/441628 

As the bulk mover has received a bug fix in the latest release to address this issue, we do no longer need to keep this open
